name: base
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9.15
  - matplotlib.pyplot
  - pandas=1.5.2
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - panel=0.14.3
  - jupyter-panel-proxy
